server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

#      콘솔 url 설정. 웹으로 접근할 수 있게
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
#     Data Definition Language
      ddl-auto: create
    show-sql: true # Rerun하면 drop table if exists user_tb casade 가 나옴. 255자.  generby 이게 auto_increment
    properties:
      hibernate:
        format_sql: true